### PR TITLE
Fixed Bot Not Leaving

### LINKED ISSUE #149: [BUG] Bot Not Leaving
**Describe the bug**
Bot stays playing songs when adding a huge playlist even when everyone leaves.

**To Reproduce**
`!!play https://open.spotify.com/playlist/4g4DBYpE4bcB520j5nzAMo?si=5e7be30cd49348e5` was the exact command run that caused this.

### PR DESCRIPTION
**Pull request by beanbeanjuice**
Fixes #149. This also makes #28 obsolete.

Changes Proposed in this Pull Request:
- Repeating command only repeats ONCE the playlist is over.
- Fixed an error where the current voice channel would return `null` and the timer would not start.

### CODE REVIEW

File: src/main/java/com/beanbeanjuice/utility/guild/CustomGuild.java [hunk 1]
```diff
@@ -310,7 +310,7 @@ public void setLastMusicChannel(TextChannel lastMusicChannel) {
     public void startAudioChecking() {
         timer = new Timer();
         final int[] seconds = {0};
-        int secondsToLeave = 300;
+        int secondsToLeave = 10;
```
Comment (beanbeanjuice) [inline src/main/java/com/beanbeanjuice/utility/guild/CustomGuild.java:313]: Change this back to 300.

**Review by beanbeanjuice — COMMENTED** [review]
Complete the changes.

**Review by beanbeanjuice — COMMENTED** [review]
Everything looks good.
